### ISSUE TITLE
you are not qualified to write a book

### ISSUE THREAD

**Issue by faiq** [DavidAwad/Computer-Architecture-for-People-with-Lives#1]
People spend their entire lives getting Phds and doing research to write books, who do you think you are?

**Comment by benhgreen** [comment]
+1

**Comment by faiq** [comment]
Thanks for the support @benhgreen

**Comment by davidawad** [comment]
I wanted to try it! I didn't say I was going to write an amazing book. Just something I wanted to try to get all my notes out in a meaningful way.

**Comment by davidawad** [comment]
I'm closing this! Stop being negative @faiq !
